# Nanopub CLI installer for Windows (PowerShell)
# Usage: irm https://nanopublication.github.io/nanopub-java/install.ps1 | iex
#
# Optional environment variable overrides (set before running):
#   $env:NANOPUB_INSTALL_DIR  — where the np.cmd launcher is placed (default: ~\.nanopub\bin)
#   $env:NANOPUB_JAR_DIR      — where the jar file is saved       (default: ~\.nanopub\lib)
#   $env:NANOPUB_VERSION      — install this version instead of the latest one

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Helpers ────────────────────────────────────────────────────────────────────

function Info    { param($Msg) Write-Host "[nanopub] $Msg" -ForegroundColor Cyan   }
function Success { param($Msg) Write-Host "[nanopub] $Msg" -ForegroundColor Green  }
function Err     {
    param($Msg)
    Write-Host "[nanopub] ERROR: $Msg" -ForegroundColor Red
    exit 1
}

# ── Resolve install paths ──────────────────────────────────────────────────────

$InstallDir = if ($env:NANOPUB_INSTALL_DIR) { $env:NANOPUB_INSTALL_DIR } `
              else { Join-Path $HOME '.nanopub\bin' }

$JarDir     = if ($env:NANOPUB_JAR_DIR)     { $env:NANOPUB_JAR_DIR }     `
              else { Join-Path $HOME '.nanopub\lib' }

# Artifacts are fetched from Maven Central rather than the GitHub release API,
# which is rate limited to 60 requests per hour per IP for anonymous callers.
$MavenBase = 'https://repo1.maven.org/maven2/org/nanopub/nanopub'

# ── Preflight checks ──────────────────────────────────────────────────────────

Info "Checking prerequisites..."

# Java
try   { $null = & java -version 2>&1 }
catch { Err "Java not found. Please install a JRE/JDK and ensure 'java' is on your PATH." }

# PowerShell 5.1+ has Invoke-WebRequest built in — no extra tools needed.
# Require at least PS 5 for good TLS 1.2 support.
if ($PSVersionTable.PSVersion.Major -lt 5) {
    Err "PowerShell 5 or later is required (you have $($PSVersionTable.PSVersion))."
}

# Windows PowerShell 5.1 may still default to TLS 1.0, which Maven Central rejects
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# ── Resolve version + download URL via Maven Central ──────────────────────────

if ($env:NANOPUB_VERSION) {
    $Version = $env:NANOPUB_VERSION
    Info "Using pinned version: $Version"
} else {
    Info "Resolving latest nanopub release..."

    try {
        $Metadata = Invoke-RestMethod -Uri "$MavenBase/maven-metadata.xml"
    } catch {
        Err "Could not reach Maven Central: $_`nCheck your internet connection."
    }

    # <release> holds the newest non-snapshot version
    $Version = $Metadata.metadata.versioning.release
    if (-not $Version) { Err "Could not determine latest version from Maven Central metadata." }

    Info "Latest version: $Version"
}

$JarName = "nanopub-${Version}-jar-with-dependencies.jar"
$JarUrl  = "$MavenBase/$Version/$JarName"
$JarPath = Join-Path $JarDir $JarName
$TmpPath = "$JarPath.tmp"

# ── Download jar ───────────────────────────────────────────────────────────────

if (-not (Test-Path $JarDir)) { New-Item -ItemType Directory -Path $JarDir | Out-Null }

if (Test-Path $JarPath) {
    Info "Jar already present at $JarPath — skipping download."
} else {
    Info "Downloading $JarName..."

    try {
        # Use a WebClient for a live progress indicator; fall back to IWR on error
        $wc = New-Object System.Net.WebClient
        $wc.DownloadFile($JarUrl, $TmpPath)
    } catch {
        Remove-Item -Force $TmpPath -ErrorAction SilentlyContinue
        Err "Download failed: $_`nURL: $JarUrl"
    }

    # Validate: jar/zip magic bytes are 0x50 0x4B ("PK")
    $bytes = [System.IO.File]::ReadAllBytes($TmpPath)
    if ($bytes.Length -lt 2 -or $bytes[0] -ne 0x50 -or $bytes[1] -ne 0x4B) {
        Remove-Item -Force $TmpPath -ErrorAction SilentlyContinue
        Err "Downloaded file is not a valid jar (bad magic bytes).`nThis usually means a proxy returned an HTML page instead of the binary.`nTry running the installer again, or download manually from:`n  $JarUrl"
    }

    Move-Item -Path $TmpPath -Destination $JarPath
}

# ── Write the np.cmd launcher ─────────────────────────────────────────────────

if (-not (Test-Path $InstallDir)) { New-Item -ItemType Directory -Path $InstallDir | Out-Null }

$LauncherPath = Join-Path $InstallDir 'np.cmd'

@"
@echo off
rem nanopub CLI launcher — auto-generated by install.ps1
java -Dsun.jnu.encoding=utf8 -Dfile.encoding=utf8 -jar "$JarPath" %*
"@ | Set-Content -Encoding ASCII -Path $LauncherPath

Success "Installed np.cmd → $LauncherPath"

# ── Add InstallDir to the user PATH (persistent) ──────────────────────────────

$RegPath    = 'HKCU:\Environment'
$CurrentPath = (Get-ItemProperty -Path $RegPath -Name Path -ErrorAction SilentlyContinue).Path

if ($CurrentPath -notlike "*$InstallDir*") {
    $NewPath = if ($CurrentPath) { "$CurrentPath;$InstallDir" } else { $InstallDir }
    Set-ItemProperty -Path $RegPath -Name Path -Value $NewPath

    # Broadcast the change so already-open Explorer/shells can pick it up
    $signature = @'
[DllImport("user32.dll", SetLastError=true, CharSet=CharSet.Auto)]
public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg,
    UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
'@
    $type = Add-Type -MemberDefinition $signature -Name WinEnv -Namespace Win32 -PassThru
    $result = [UIntPtr]::Zero
    $type::SendMessageTimeout([IntPtr]0xFFFF, 0x001A, [UIntPtr]::Zero,
        'Environment', 2, 5000, [ref]$result) | Out-Null

    Info "Added $InstallDir to your user PATH."
} else {
    Info "$InstallDir already present in PATH — no changes needed."
}

# ── Final instructions ────────────────────────────────────────────────────────

Write-Host ""
Success "nanopub $Version installed successfully!"
Write-Host ""
Write-Host "  Open a new terminal window, then run:"
Write-Host ""
Write-Host "    np check nanopubfile.trig"
Write-Host ""
Write-Host "  Tip: set `$env:NANOPUB_INSTALL_DIR or `$env:NANOPUB_JAR_DIR before"
Write-Host "  running this script to customize installation paths, or"
Write-Host "  `$env:NANOPUB_VERSION to install a specific version."
Write-Host ""
