#!/bin/bash
# Nanopub CLI installer
# Usage: curl -LsSf https://nanopublication.github.io/nanopub-java/install.sh | bash

set -e

INSTALL_DIR="${NANOPUB_INSTALL_DIR:-$HOME/.nanopub/bin}"
JAR_DIR="${NANOPUB_JAR_DIR:-$HOME/.nanopub/lib}"

# Artifacts are fetched from Maven Central rather than the GitHub release API,
# which is rate limited to 60 requests per hour per IP for anonymous callers.
MAVEN_BASE="https://repo1.maven.org/maven2/org/nanopub/nanopub"

# ── Helpers ────────────────────────────────────────────────────────────────────

info()    { printf '\033[1;34m[nanopub]\033[0m %s\n' "$*"; }
success() { printf '\033[1;32m[nanopub]\033[0m %s\n' "$*"; }
error()   { printf '\033[1;31m[nanopub]\033[0m %s\n' "$*" >&2; exit 1; }

need_cmd() {
  command -v "$1" &>/dev/null || error "Required command not found: $1"
}

# ── Preflight checks ──────────────────────────────────────────────────────────

need_cmd curl
need_cmd java

# ── Resolve version + download URL via Maven Central ──────────────────────────

if [ -n "$NANOPUB_VERSION" ]; then
  VERSION="$NANOPUB_VERSION"
  info "Using pinned version: $VERSION"
else
  info "Resolving latest nanopub release..."

  METADATA=$(curl -fsSL "$MAVEN_BASE/maven-metadata.xml") \
    || error "Could not reach Maven Central. Check your internet connection."

  # <release> holds the newest non-snapshot version
  VERSION=$(printf '%s' "$METADATA" \
    | tr '<' '\n' \
    | grep '^release>' \
    | head -1 \
    | sed 's/^release>//')

  [ -z "$VERSION" ] && error "Could not determine latest version from Maven Central metadata."

  info "Latest version: $VERSION"
fi

JAR_NAME="nanopub-${VERSION}-jar-with-dependencies.jar"
JAR_URL="$MAVEN_BASE/$VERSION/$JAR_NAME"

# ── Download jar ───────────────────────────────────────────────────────────────

JAR_PATH="$JAR_DIR/$JAR_NAME"
TMP_PATH="${JAR_PATH}.tmp"

mkdir -p "$JAR_DIR"

if [ -f "$JAR_PATH" ]; then
  info "Jar already present at $JAR_PATH — skipping download."
else
  info "Downloading $JAR_NAME..."

  # Download to a temp file first so a failed download never leaves a corrupt jar
  curl -fL --progress-bar --output "$TMP_PATH" "$JAR_URL" \
    || { rm -f "$TMP_PATH"; error "Download failed. URL: $JAR_URL"; }

  # Validate: a jar is a zip file — its first two bytes must be "PK"
  MAGIC=$(dd if="$TMP_PATH" bs=2 count=1 2>/dev/null | od -A n -t x1 | tr -d ' \n')
  if [ "$MAGIC" != "504b" ]; then
    rm -f "$TMP_PATH"
    error "Downloaded file is not a valid jar (bad magic bytes: $MAGIC). \
This usually means a proxy returned an HTML page instead of the binary. \
Try running the installer again, or download manually from: $JAR_URL"
  fi

  mv "$TMP_PATH" "$JAR_PATH"
fi

# ── Write the np launcher script ──────────────────────────────────────────────

mkdir -p "$INSTALL_DIR"

NP_SCRIPT="$INSTALL_DIR/np"

cat > "$NP_SCRIPT" <<EOF
#!/bin/bash
# nanopub CLI launcher — auto-generated by install.sh
JAVAPARAMS="-Dsun.jnu.encoding=utf8 -Dfile.encoding=utf8"
exec java \$JAVAPARAMS -jar "$JAR_PATH" "\$@"
EOF

chmod +x "$NP_SCRIPT"

success "Installed np → $NP_SCRIPT"

# ── Shell PATH configuration ──────────────────────────────────────────────────

# Detect which shell config files to update
SHELL_CONFIGS=()
[ -f "$HOME/.bashrc"              ] && SHELL_CONFIGS+=("$HOME/.bashrc")
[ -f "$HOME/.bash_profile"        ] && SHELL_CONFIGS+=("$HOME/.bash_profile")
[ -f "$HOME/.zshrc"               ] && SHELL_CONFIGS+=("$HOME/.zshrc")
[ -f "$HOME/.config/fish/config.fish" ] && SHELL_CONFIGS+=("$HOME/.config/fish/config.fish")

PATH_LINE="export PATH=\"$INSTALL_DIR:\$PATH\""
FISH_LINE="fish_add_path \"$INSTALL_DIR\""

ADDED_TO=()
for cfg in "${SHELL_CONFIGS[@]}"; do
  if ! grep -qF "$INSTALL_DIR" "$cfg" 2>/dev/null; then
    if [[ "$cfg" == *.fish ]]; then
      echo "$FISH_LINE" >> "$cfg"
    else
      printf '\n# Added by nanopub installer\n%s\n' "$PATH_LINE" >> "$cfg"
    fi
    ADDED_TO+=("$cfg")
  fi
done

if [ "${#ADDED_TO[@]}" -gt 0 ]; then
  info "Added $INSTALL_DIR to PATH in: ${ADDED_TO[*]}"
else
  info "$INSTALL_DIR already present in PATH config."
fi

# ── Final instructions ────────────────────────────────────────────────────────

echo ""
success "nanopub $VERSION installed successfully!"
echo ""
echo "  To start using it, reload your shell:"
echo ""
echo "    source ~/.bashrc   # or ~/.zshrc, etc."
echo ""
echo "  Then run:"
echo ""
echo "    np check nanopubfile.trig"
echo ""
echo "  Tip: set NANOPUB_INSTALL_DIR or NANOPUB_JAR_DIR before running this"
echo "  script to customize installation paths, or NANOPUB_VERSION to install"
echo "  a specific version instead of the latest one."
echo ""
