site_name: nanopub-java
site_description: Java client for Nanopublications
site_author: Robin Richardson, Sven van der Burg, Vincent Emonet
site_url: https://nanopublication.github.io/nanopub-java
repo_name: Nanopublication/nanopub-java
repo_url: https://github.com/Nanopublication/nanopub-java
edit_uri: "edit/main/docs/"
copyright: Copyright &copy; 2020 Robin Richardson, Sven van der Burg

nav:
  - Getting started:
      - Getting started: index.md
      - What are Nanopublications?: getting-started/what-are-nanopubs.md
      - Setup instructions: getting-started/setup.md
  - Create: create.md
  - Sign: sign.md
  - Publish: publish.md

theme:
  name: "material"
  favicon: assets/icon.png
  logo: assets/icon.png
  # icon:
  #   logo: material/microscope
  language: en
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.instant
    # - navigation.tabs.sticky


plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true

watch:
  - docs


# Styled blocks: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - smarty


  #extra_css:
  #- assets/custom.css

  #extra_javascript:
  #- assets/fontawesome.min.js
  #- assets/solid.min.js

extra:
  social:
    #- icon: fontawesome/brands/python
    #  link: https://pypi.org/project/nanopub
    - icon: fontawesome/brands/github
      link: https://github.com/Nanopublication/nanopub-java
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/nanopub/nanopub-java
